[profile.default]
solc_version = "0.8.26"
optimizer = true
optimizer_runs = 1_000_000
evm_version = "cancun"
src = "src"
test = "test"
libs = ["lib"]
ffi = true
viaIR = true
auto_detect_remappings = false
remappings = [
  "@uniswap/v4-core/=lib/v4-core/",
  "@uniswap/v4-periphery/=lib/v4-periphery/",
  "@openzeppelin/=lib/openzeppelin-contracts/",
  "solmate/=lib/solmate/",
  "forge-std/=lib/forge-std/src/"
]

[fmt]
line_length = 100
tab_width = 4

[rpc_endpoints]
mainnet = "${MAINNET_RPC_URL}"
sepolia = "${SEPOLIA_RPC_URL}"